######################################################################
# Automatically generated by qmake (3.0) K nov. 6 10:35:35 2018
######################################################################

QT += testlib core gui
TEMPLATE = app
TARGET = test
INCLUDEPATH += .

# Input
HEADERS += model.h specia_timer.h test.h
SOURCES += model.cpp specia_timer.cpp test.cpp
