######################################################################
# Automatically generated by qmake (3.0) Cs nov. 1 07:45:03 2018
######################################################################

QT += testlib
TEMPLATE = app
TARGET = test
INCLUDEPATH += .

# Input
HEADERS += model.h test.h
SOURCES += model.cpp test.cpp
